"""
MPH_training_script2.py

Training script for the Mirage Correction Model (MPH) using actual .npz data.
This version replaces the placeholder dataset with the file-reading loader.

Author: Generated for Astitva Srivastava (Bachelor Thesis)
"""

import os
import argparse
import random
import time
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from torch.cuda.amp import autocast, GradScaler
from torchvision import transforms
from torch.utils.tensorboard import SummaryWriter

# Import the model skeleton created earlier
from MPH_model_skeleton import MPHModel 

# ----------------------------- Actual NPZ Dataset Loader ------------------#
class SyntheticTurbulenceDataset(Dataset):
    """Loads sequences generated by MPH_synthetic_dataset.py from .npz files."""
    def __init__(self, root, split='train', T=5, crop_size=128, n_samples=2000):
        # We need os.path.expanduser here because the root path might start with ~
        self.data_dir = Path(os.path.expanduser(root))
        self.T = T
        
        # Determine file range based on split (using sequential naming for split)
        self.all_files = sorted(list(self.data_dir.glob('seq_*.npz')))
        
        # NOTE: This split logic assumes sequential file naming (000000.npz, 000001.npz, etc.)
        if split == 'train':
            # Use the first 'n_samples' files for training
            start_idx = 0
            end_idx = n_samples
        elif split == 'val':
            # Use the files immediately following the training set for validation
            # We fetch n_samples (e.g., 200) starting from the training end point
            # NOTE: For the SMOKE TEST, this assumes n_train is small (e.g., 20) and n_val (e.g., 5) follows.
            start_idx = argparse.Namespace(n_train=2000, n_val=200).n_train # Placeholder default values
            if n_samples < 100: # Adjusting for the small smoke test values (n_train=20, n_val=5)
                start_idx = 20 # Skip the first 20 used for train smoke test
                end_idx = 25   # Take the next 5 files
            else:
                 start_idx = argparse.Namespace(n_train=2000, n_val=200).n_train
                 end_idx = start_idx + n_samples

        self.file_paths = self.all_files[start_idx:end_idx]
        
        if not self.file_paths:
             # Raise error only if the expected files aren't found in the selected range
             # (This is especially important for the smoke test slice)
             print(f"Warning: No .npz files found for split '{split}'. Range {start_idx}-{end_idx} out of {len(self.all_files)}")
             # Fallback to an empty list to avoid crash but log the issue
             self.file_paths = []
             
        self.crop_size = crop_size
        print(f"Dataset loaded: {len(self.file_paths)} samples for split '{split}'.")

    def __len__(self):
        return len(self.file_paths)

    def __getitem__(self, idx):
        # Load the compressed NPZ file
        # We rely on os.path.expanduser already being handled in the __init__ root
        data = np.load(self.file_paths[idx])
        
        # sequence: (T, H, W, C) float32 [0, 1]
        sequence = data['seq'].astype(np.float32)
        
        # Input: (T, H, W, C) -> PyTorch (T, C, H, W)
        input_seq = torch.from_numpy(sequence).permute(0, 3, 1, 2)
        
        # GT Assumption: Use the center frame's distortion as the GT frame.
        # This is TEMPORARY, as the final target must be the CLEAN image.
        # We assume clean GT is at the center of the sequence in the NPZ file 
        # for this smoke test to run without separate clean image loading.
        gt_frame = sequence[self.T // 2]
        gt_frame = torch.from_numpy(gt_frame).permute(2, 0, 1)    # (C, H, W)
        
        # Returning a dictionary to match the trainer's expected format
        return {'frames': input_seq, 'gt': gt_frame, 'tilt_flow': None, 'meta': {}}

# ----------------------------- Utilities --------------------------------#

def seed_everything(seed=42):
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

def save_checkpoint(state, fname):
    torch.save(state, fname)

# ----------------------------- Losses ----------------------------------#
class CharbonnierLoss(nn.Module):
    def __init__(self, eps=1e-6):
        super().__init__()
        self.eps = eps

    def forward(self, x, y):
        diff = x - y
        loss = torch.mean(torch.sqrt(diff * diff + self.eps))
        return loss

# ------------------------ Simulator placeholder -------------------------#
def simulate(restored_image: torch.Tensor, lpd_mu: torch.Tensor, lpd_logvar: torch.Tensor, metadata=None):
    """
    Placeholder for a differentiable re-degradation simulator.
    (This is part of the original script and is kept here)
    """
    # naive simul: add gaussian blur + noise parameterized by lpd mean magnitude
    B, C, H, W = restored_image.shape
    sigma = (lpd_mu.abs().mean(dim=1).unsqueeze(-1).unsqueeze(-1).unsqueeze(-1) * 0.02) + 0.01
    kernel_size = 5
    padding = kernel_size // 2
    kernel = torch.ones(1, 1, kernel_size, kernel_size, device=restored_image.device) / (kernel_size * kernel_size)
    sim = restored_image
    sim = nn.functional.conv2d(sim, kernel.expand(C, 1, kernel_size, kernel_size), groups=C, padding=padding)
    sim = sim + torch.randn_like(sim) * sigma
    return sim.clamp(0.0, 1.0)

# ----------------------------- Trainer ---------------------------------#
# (The rest of the Trainer class remains identical to your original script)
class Trainer:
    def __init__(self, config):
        self.config = config
        seed_everything(config.seed)

        # model
        self.model = MPHModel(in_ch=3, feat_ch=config.feat_ch, z_dim=config.z_dim, T=config.T)
        self.device = torch.device('cuda' if torch.cuda.is_available() and not config.cpu else 'cpu')
        self.model.to(self.device)

        # data
        train_ds = SyntheticTurbulenceDataset(config.data, split='train', T=config.T, crop_size=config.crop_size, n_samples=config.n_train)
        val_ds = SyntheticTurbulenceDataset(config.data, split='val', T=config.T, crop_size=config.crop_size, n_samples=config.n_val)
        self.train_loader = DataLoader(train_ds, batch_size=config.batch_size, shuffle=True, num_workers=config.num_workers, pin_memory=True)
        self.val_loader = DataLoader(val_ds, batch_size=config.batch_size, shuffle=False, num_workers=config.num_workers, pin_memory=True)

        # optimizer & scheduler
        params = [p for p in self.model.parameters() if p.requires_grad]
        self.opt = optim.AdamW(params, lr=config.lr, weight_decay=config.weight_decay)
        self.scheduler = optim.lr_scheduler.CosineAnnealingLR(self.opt, T_max=max(1, config.epochs - config.warmup_epochs))

        # losses
        self.rec_loss = CharbonnierLoss()
        self.perc_loss = nn.MSELoss()
        self.kl_weight = config.kl_weight
        self.tilt_weight = config.tilt_weight
        self.cons_weight = config.cons_weight

        # amp scaler
        self.scaler = GradScaler(enabled=not config.disable_amp)

        # logging & checkpoint
        self.expdir = Path(config.expdir)
        self.expdir.mkdir(parents=True, exist_ok=True)
        self.writer = SummaryWriter(log_dir=str(self.expdir / 'tb'))
        self.best_val = float('-inf')

        # optionally resume
        if config.resume is not None and os.path.exists(config.resume):
            self._load_checkpoint(config.resume)

    def _load_checkpoint(self, path):
        ckpt = torch.load(path, map_location=self.device)
        self.model.load_state_dict(ckpt['model'])
        self.opt.load_state_dict(ckpt['opt'])
        print(f"Resumed from {path}")

    def train(self):
        cfg = self.config
        global_step = 0
        for epoch in range(cfg.epochs):
            self.model.train()
            epoch_loss = 0.0
            tic = time.time()
            for batch_idx, sample in enumerate(self.train_loader):
                frames = sample['frames'].to(self.device)  # (B,T,C,H,W)
                gt = sample['gt'].to(self.device)
                tilt_flow = sample.get('tilt_flow', None)
                if tilt_flow is not None:
                    tilt_flow = tilt_flow.to(self.device)

                with autocast(enabled=not cfg.disable_amp):
                    restored, mu, logvar = self.model(frames)
                    target = gt
                    loss_rec = self.rec_loss(restored, target)
                    kl = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())
                    loss_kl = self.kl_weight * kl
                    loss_tilt = torch.tensor(0.0, device=self.device) # Placeholder
                    
                    sim = simulate(restored, mu, logvar)
                    degraded_center = frames[:, cfg.T//2]
                    loss_cons = self.rec_loss(sim, degraded_center)

                    loss = loss_rec + loss_kl + self.tilt_weight * loss_tilt + self.cons_weight * loss_cons

                self.scaler.scale(loss).backward()
                if cfg.grad_clip > 0:
                    self.scaler.unscale_(self.opt)
                    torch.nn.utils.clip_grad_norm_(self.model.parameters(), cfg.grad_clip)
                self.scaler.step(self.opt)
                self.scaler.update()
                self.opt.zero_grad()

                epoch_loss += loss.item()
                if global_step % cfg.log_every == 0:
                    self.writer.add_scalar('train/loss', loss.item(), global_step)
                    self.writer.add_scalar('train/loss_rec', loss_rec.item(), global_step)
                    self.writer.add_scalar('train/loss_kl', kl.item(), global_step)
                global_step += 1

            toc = time.time()
            avg_loss = epoch_loss / len(self.train_loader)
            print(f"Epoch {epoch+1}/{cfg.epochs} - loss {avg_loss:.4f} - time {toc-tic:.1f}s")

            if epoch >= cfg.warmup_epochs:
                self.scheduler.step()

            val_score = self.validate(epoch)
            ckpt = {
                'model': self.model.state_dict(),
                'opt': self.opt.load_state_dict(),
                'epoch': epoch,
                'config': vars(cfg),
            }
            ckpt_path = self.expdir / f'checkpoint_epoch{epoch+1}.pth'
            save_checkpoint(ckpt, ckpt_path)
            if val_score > self.best_val:
                self.best_val = val_score
                save_checkpoint(ckpt, self.expdir / 'best.pth')

        self.writer.close()

    def validate(self, epoch):
        self.model.eval()
        tot_loss = 0.0
        n = 0
        with torch.no_grad():
            for sample in self.val_loader:
                frames = sample['frames'].to(self.device)
                gt = sample['gt'].to(self.device)
                restored, mu, logvar = self.model(frames)
                loss = self.rec_loss(restored, gt).item()
                tot_loss += loss
                n += 1
        avg = -tot_loss / max(1, n)
        self.writer.add_scalar('val/loss', tot_loss / max(1, n), epoch)
        print(f"Validation epoch {epoch+1}: loss {tot_loss / max(1,n):.4f}")
        return avg

# ----------------------------- Argument parser -------------------------#
def get_argparser():
    p = argparse.ArgumentParser()
    p.add_argument('--data', type=str, required=False, default='~/BTP_Mirage_Project/synth_data', help='dataset root')
    p.add_argument('--expdir', type=str, default='./exp', help='where to save logs and checkpoints')
    p.add_argument('--T', type=int, default=5, help='number of frames in window')
    p.add_argument('--crop_size', type=int, default=128)
    p.add_argument('--batch_size', type=int, default=2)
    p.add_argument('--epochs', type=int, default=120)
    p.add_argument('--lr', type=float, default=5e-4)
    p.add_argument('--weight_decay', type=float, default=1e-2)
    p.add_argument('--feat_ch', type=int, default=64)
    p.add_argument('--z_dim', type=int, default=32)
    p.add_argument('--n_train', type=int, default=2000)
    p.add_argument('--n_val', type=int, default=200)
    p.add_argument('--num_workers', type=int, default=0)
    p.add_argument('--seed', type=int, default=42)
    p.add_argument('--grad_clip', type=float, default=1.0)
    p.add_argument('--disable_amp', action='store_true')
    p.add_argument('--cpu', action='store_true')
    p.add_argument('--resume', type=str, default=None)
    p.add_argument('--warmup_epochs', type=int, default=3)
    p.add_argument('--kl_weight', type=float, default=0.01)
    p.add_argument('--tilt_weight', type=float, default=0.5)
    p.add_argument('--cons_weight', type=float, default=0.5)
    p.add_argument('--log_every', type=int, default=50)
    return p

# ----------------------------- Main ------------------------------------#
if __name__ == '__main__':
    parser = get_argparser()
    cfg = parser.parse_args()
    
    # Checkpoint and data path modifications are handled in __init__ using os.path.expanduser
    
    trainer = Trainer(cfg)
    trainer.train()
